-- =============================================
-- LegisSwipe Database Schema
-- Run this in your Supabase SQL editor
-- =============================================

-- BILLS TABLE
CREATE TABLE bills (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  external_id TEXT UNIQUE NOT NULL,        -- e.g. "congress:hr1234-118" or "legiscan:1234567"
  title TEXT NOT NULL,
  summary TEXT,                             -- Generated by Groq. NULL until processed.
  sponsor_name TEXT,
  sponsor_state TEXT,                       -- 2-letter state code
  level TEXT NOT NULL CHECK (level IN ('federal', 'state')),
  state TEXT,                               -- NULL for federal, 2-letter code for state bills
  status TEXT,                              -- Current bill status
  introduced_date DATE,
  source TEXT NOT NULL CHECK (source IN ('congress', 'legiscan')),
  is_fluff BOOLEAN DEFAULT FALSE,           -- TRUE = filtered out, won't appear in game
  fluff_reason TEXT,                        -- Why it was filtered (for debugging)
  is_summarized BOOLEAN DEFAULT FALSE,      -- TRUE = summary generated
  raw_text TEXT,                            -- First ~3000 chars of bill text for summarization
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- COMPARISONS TABLE (the ranked-choice dataset)
CREATE TABLE comparisons (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_a_id UUID NOT NULL REFERENCES bills(id),
  bill_b_id UUID NOT NULL REFERENCES bills(id),
  winner_id UUID NOT NULL REFERENCES bills(id),
  user_state TEXT,                          -- What state filter the user had active
  session_id TEXT NOT NULL,                 -- Anonymous session UUID from browser
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Enforce winner must be one of the two bills
  CONSTRAINT winner_must_be_a_or_b CHECK (winner_id = bill_a_id OR winner_id = bill_b_id),
  -- Enforce consistent ordering to prevent duplicate pairs
  CONSTRAINT pair_ordering CHECK (bill_a_id < bill_b_id)
);

-- SEEN PAIRS TABLE (per session — prevents showing same matchup twice)
CREATE TABLE seen_pairs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id TEXT NOT NULL,
  bill_a_id UUID NOT NULL REFERENCES bills(id),
  bill_b_id UUID NOT NULL REFERENCES bills(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT seen_pair_ordering CHECK (bill_a_id < bill_b_id),
  UNIQUE (session_id, bill_a_id, bill_b_id)
);

-- API REQUEST COUNTER (tracks LegiScan usage to stay within 30k/month limit)
CREATE TABLE api_usage (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  source TEXT NOT NULL CHECK (source IN ('congress', 'legiscan')),
  operation TEXT NOT NULL,          -- e.g. 'getMasterList', 'getBill', 'getBillText'
  month TEXT NOT NULL,              -- e.g. '2026-03' — for monthly rollup
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_api_usage_source_month ON api_usage(source, month);

-- Quick view: how many LegiScan calls this month?
CREATE VIEW legiscan_monthly_usage AS
SELECT
  month,
  COUNT(*) AS total_requests,
  30000 - COUNT(*) AS remaining,
  ROUND(COUNT(*)::DECIMAL / 30000 * 100, 1) AS pct_used
FROM api_usage
WHERE source = 'legiscan'
GROUP BY month
ORDER BY month DESC;

-- INDEXES
CREATE INDEX idx_bills_level ON bills(level);
CREATE INDEX idx_bills_state ON bills(state);
CREATE INDEX idx_bills_is_fluff ON bills(is_fluff);
CREATE INDEX idx_bills_is_summarized ON bills(is_summarized);
CREATE INDEX idx_bills_source ON bills(source);
CREATE INDEX idx_comparisons_winner ON comparisons(winner_id);
CREATE INDEX idx_comparisons_session ON comparisons(session_id);
CREATE INDEX idx_comparisons_created ON comparisons(created_at);
CREATE INDEX idx_seen_pairs_session ON seen_pairs(session_id);

-- VIEW: Bill win rates (useful for your data analysis)
CREATE VIEW bill_win_rates AS
SELECT
  b.id,
  b.title,
  b.summary,
  b.sponsor_name,
  b.sponsor_state,
  b.level,
  b.state,
  b.status,
  COUNT(c.id) AS total_appearances,
  COUNT(CASE WHEN c.winner_id = b.id THEN 1 END) AS wins,
  ROUND(
    COUNT(CASE WHEN c.winner_id = b.id THEN 1 END)::DECIMAL /
    NULLIF(COUNT(c.id), 0) * 100, 2
  ) AS win_rate_pct
FROM bills b
LEFT JOIN comparisons c ON (c.bill_a_id = b.id OR c.bill_b_id = b.id)
WHERE b.is_fluff = FALSE AND b.is_summarized = TRUE
GROUP BY b.id
ORDER BY win_rate_pct DESC NULLS LAST;

-- RLS: Enable row-level security (Supabase best practice)
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE comparisons ENABLE ROW LEVEL SECURITY;
ALTER TABLE seen_pairs ENABLE ROW LEVEL SECURITY;

-- Allow public read on bills
CREATE POLICY "Bills are publicly readable" ON bills FOR SELECT USING (true);

-- Allow public insert on comparisons and seen_pairs (anonymous voting)
CREATE POLICY "Anyone can record a vote" ON comparisons FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can read comparisons" ON comparisons FOR SELECT USING (true);
CREATE POLICY "Anyone can record seen pairs" ON seen_pairs FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can read their seen pairs" ON seen_pairs FOR SELECT USING (true);

-- API usage — only service role can write, public can read (for dashboard)
ALTER TABLE api_usage ENABLE ROW LEVEL SECURITY;
CREATE POLICY "API usage is publicly readable" ON api_usage FOR SELECT USING (true);

-- Service role (cron jobs) has full access via service role key — no policy needed for that
